### ISSUE TITLE
[1.10.2]confirmed:cave&ravine generation issue with RTG

### ISSUE THREAD

**Issue by touhouzun** [defeatedcrow/HeatAndClimateLib#10]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version:1.10.2-12.18.3.2511
- RTG version:1.10.2-4.2.0.0-snapshot-5
- HeatAndClimateLib:1.10.2-2.2.2(1.6.x is the same)

##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)
![default](https://user-images.githubusercontent.com/31458903/36715508-82075838-1bd1-11e8-8e0e-09e2b5227ef2.PNG)
![1](https://user-images.githubusercontent.com/31458903/36715510-844e220c-1bd1-11e8-9801-76a96ebb0f24.PNG)
![2](https://user-images.githubusercontent.com/31458903/36715515-87ec745e-1bd1-11e8-8e54-c73e9ce9fcf3.PNG)
![3](https://user-images.githubusercontent.com/31458903/36715522-8a2f7482-1bd1-11e8-962d-f3446e161b14.PNG)
![2018-02-27_15 07 48](https://user-images.githubusercontent.com/31458903/36715526-8c4e75f6-1bd1-11e8-9f89-af5986e310cd.png)
![2018-02-27_15 07 50](https://user-images.githubusercontent.com/31458903/36715530-8e2efecc-1bd1-11e8-930c-285f88ac0491.png)
![2018-02-27_15 07 55](https://user-images.githubusercontent.com/31458903/36715531-8f7b0db6-1bd1-11e8-8562-c2ba359785ed.png)

##### Steps to reproduce the issue: (If it's easily reproducible.)

1.install the two mods mentioned,configs above
2.create a new rtg world
3.gamemode 3 and dive down

##### Extra Information:
- If you have a crashlog, please provide it by using http://pastebin.com/ or https://gist.github.com/
- You can also provide your client log file: /.minecraft/logs/fml-client-latest.log
- If your client log file is too big for pastebin you can use https://gist.github.com/

extra links,to introduce what RTG is:
https://github.com/Team-RTG/Realistic-Terrain-Generation
Apologize for my bad english.I can't speak Japanese.
(Thanks to ctrl+c & ctrl+v)

**Comment by defeatedcrow** [comment]
Please change the config file. It can be changed arbitrarily by the user.
Open "config \ defeatedcrow \ climate \ core.cfg" file.
Next, set "Enable Water Caves" to "false".
This flag stops modification of underground generation by HaC.

**Comment by touhouzun** [comment]
Thanks!It really works!
![default](https://user-images.githubusercontent.com/31458903/36832049-fa5aa4f4-1d64-11e8-83d4-3a07d5fef780.PNG)
![2018-03-01_15 24 47](https://user-images.githubusercontent.com/31458903/36832064-04730742-1d65-11e8-8f5d-0c31be8048ba.png)
