### ISSUE TITLE
Sunlight Badge cannot repair tool held in off-hand

### ISSUE THREAD

**Issue by Iunius118** [defeatedcrow/HeatAndClimateLib#22]
forge1.12.2-14.23.5.2768
HeatAndClimateLib_1.12.2-3.1.0
HeatAndClimateMod_1.12.2-3.1.0

陽光のバッジをインベントリの上段に置いてオフハンドに消耗したツールを持ち、その状態でしばらくの間（20分程度）待ちましたが、ツールの耐久度は回復していませんでした。

![2019-07-15_13 40 02](https://user-images.githubusercontent.com/18502177/61195903-1fffa200-a706-11e9-8ba3-77598f78953c.png)

**Comment by defeatedcrow** [comment]
Thank you for your report!
It fixed in https://github.com/defeatedcrow/HeatAndClimateMod/commit/5c8b95e55e5c6c587d50ea9355c0c163096aca74.
