### ISSUE TITLE
Crash at version 3.3.1_dev (1.12.2-forge2847)

### ISSUE THREAD

**Issue by WuzgXY-GitHub** [defeatedcrow/HeatAndClimateLib#24]
[crash-2020-04-19_21.02.04-client.txt](https://github.com/defeatedcrow/HeatAndClimateLib/files/4499080/crash-2020-04-19_21.02.04-client.txt)

Crash report here

**Comment by WuzgXY-GitHub** [comment]
There's no crash at version 3.3.1 not for developers

**Comment by defeatedcrow** [comment]
dev version is a build prepared for modder, not for gameplay.
Crashing is the correct behavior.

**Comment by WuzgXY-GitHub** [comment]
> 
> 
> dev version is a build prepared for modder, not for gameplay.
> Crashing is the correct behavior.

Thank you for replying, I thought it is a kind of testing version or something else like that.
