### ISSUE TITLE
[Doubt] Where's the maven repo?

### ISSUE THREAD

**Issue by gatoborrachon** [defeatedcrow/HeatAndClimateLib#26]
sorry for the noob question, i looked at the README.md but i can't find the maven repo, where is it supposed to be?

**Comment by defeatedcrow** [comment]
Maven server is not available. (They are provided by each modder at their own expense, so I don't have them. This project has no income.)

HaCLib has a deobf version for developers. (HeatAndClimateLib_1.12.2-X.X.X_dev.jar.)
https://github.com/defeatedcrow/HeatAndClimateLib/releases
It can be introduced into the development environment in the same way as before 1.7.10.
Also, HaCMod does not have a deobf version package, but it can be installed as a library as well. (It's not a deobf version, so it only contains class files.)

**Comment by defeatedcrow** [comment]
(I will add it just in case.) It is a commentary article on my site about how to introduce mod to the development environment without using maven. This method is the one I usually use.

This is an article written in Japanese, so please use Google Translate etc.

https://defeatedcrow.jp/modwiki/%E9%96%8B%E7%99%BA%E7%92%B0%E5%A2%83%E3%82%92%E4%BD%9C%E3%82%8B2%E3%83%BB%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E7%B7%A8#dependency.E3.81.AE.E8.A8.AD.E5.AE.9A

**Comment by gatoborrachon** [comment]
many thanks, i will look it
